#!/bin/bash
# upddate pip and other installation dependencies
python3 -m pip install --upgrade pip setuptools virtualenv
# create virtual environment
python3 -m virtualenv kivy_venv
# activate the virtual enviroment for linux or macOS
source kivy_venv/bin/activate
# install Kivy
python3 -m pip install "kivy[base]" kivy_examples
# run the program
python3 main.py
